layer5labs/meshery-extensions-packages

.github/workflows/publish.yml
=> remove macOS from workflows

.github/workflows/publish.yml
1. Move to away from personal account to a service account.
2. Move away from per repo secret to org-level secret.
=> change workflow token

.github/workflows/extension-test.yml, cypress.json, cypress/fixtures/example.json, cypress/integration/e2e/login_spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js
Signed-off-by: Abhishek-kumar09 <abhimait1909@gmail.com>
- Set github workflow for e2e test
- trigger on release
- upload recording as a github artifact on test failure
=> [cy/test] Initialise e2e extension test and setup github workflow

.github/workflows/extension-test.yml
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
=> [Cl] Fix failing workflow

.github/workflows/update-extension-release.yaml
…sions
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> GitHub Workflow to update list of extension versions in meshery-extensions

.github/workflows/extension-test.yml
=> validate yaml for e2e test

.github/workflows/extension-test.yml
=> Add cypress record key

.github/workflows/extension-test.yml
=> move correct cypress json file

cypress/integration/e2e/design.js
Signed-off-by: Abhishek Kumar <abhimait1909@gmail.com>
=> Fix/cy: canvas is covered by rjsf form

cypress/integration/e2e/application_spec.js
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
Initial test to load an application --> rename --> save --> search on canvas
This PR fixes #CU-2p7c37r
The saving of the Application is failing (commented) and needs to be fixed.
=> [Cypress] Initial tests for Applications | CU-2p7c37r

.github/workflows/extension-test-dispatch-responder.yml, .github/workflows/extension-test-on-pr.yml
=> Setup: Pull-request dispatch action responder

.github/workflows/extension-test-dispatch-responder.yml, .github/workflows/extension-test-on-pr.yml
=> [Fix] typo: GH_ACCESS TOKEN

.github/workflows/extension-test.yml
=> Fix Failing Build on release trigger.

.github/workflows/extension-test-on-pr.yml
=> use different approach for PR comment to get rid of one extra action

.github/workflows/extension-test-dispatch-responder.yml, .github/workflows/extension-test-on-pr.yml
=> change name of reponder and comment on PR if cypress fails

.github/workflows/extension-test-on-pr.yml, .github/workflows/extension-test.yml
=> fix: failing each cypress test without even running

cypress/integration/e2e/component_spec.js, cypress/integration/e2e/design_spec.js
=> [Cypress] Component Drop test fixes due to RJSF wrapping cyto-canvas

.github/workflows/extension-test-on-pr.yml
=> [Minor] Changes in Message strings

cypress/integration/e2e/application_spec.js, cypress/integration/e2e/component_spec.js, cypress/integration/e2e/design_spec.js, cypress/integration/e2e/login_spec.js
component spec is skipped until pointer-up issue is fixed.
=> [Tests] Fix Cypress Spec Tests

cypress/integration/e2e/filter_spec.js
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
Filters spec
Currently, tests will fail for filters, because we don't drop and perform the actions on filters, written only the use-case tests.
=> [Cypress] Filters spec | CU-2p7c357

.github/workflows/extension-test-on-pr.yml
=> fix: Unable to find an artifact with the name: meshery-extension-ui

.github/workflows/extension-test-on-pr.yml
=> fix: provider files relocation problems

cypress/integration/e2e/design_spec.js, cypress/integration/e2e/filter_spec.js
=> fixes: Cypress tests

cypress/integration/e2e/application_spec.js, cypress/integration/e2e/component_spec.js, cypress/integration/e2e/design_spec.js, package-lock.json, package.json
=> minor changes in cy fixes

.github/workflows/extension-test-on-pr.yml, cypress/integration/e2e/login_spec.js, cypress/integration/plugin_test/visualizer_spec.js
=> [e2e/visualizer]: enable post release visualizer test

.github/workflows/extension-test.yml
=> fire tests on extensions-packages PR

.github/workflows/extension-test-on-pr.yml
=> comment extension build failure if there is.

cypress/integration/e2e/machine_spec.js
Signed-off-by: Gaurav Chadha <65453826+Chadha93@users.noreply.github.com>
Skip a failing machine test temporarily. 
=> [Cypress] Skip a failing machine test (temp).

cypress/integration/e2e/design_spec.js, cypress/integration/e2e/machine_spec.js
=> [cypress] Fixes to some tests

.github/workflows/extension-test-on-pr.yml
=> Golang to 1.19

.github/workflows/email/verify-email.html
Signed-off-by: Nikhil Ladha <nikhilladha1999@gmail.com>
=> Update email template

.github/workflows/extension-test-on-pr.yml, .github/workflows/extension-test.yml, cypress/e2e/e2e/application_spec.js, cypress/e2e/e2e/design_spec.js
=> [cypress] Fix Worklow failure and common causes of validation failures in design and applications

.github/workflows/synthetic-test.yml
=> add port forward

.github/workflows/synthetic-test.yml
=> add manual trigger

.github/workflows/synthetic-test.yml
=> updated monitoring workflow

.github/workflows/synthetic-test.yml
=> change alert account

test/main.go
=> update monitor account

.github/workflows/synthetic-test.yml, test/main.go
=> remove log line

.github/workflows/meshery-cloud-release.yml
Reverts layer5labs/meshery-extensions-packages#78
=> Revert "update workflow"

.github/workflows/meshery-cloud-release.yml
This PR adds a workflow to update Meshery Cloud docs API version with appropriate release version.
=> [chore] doc workflow

.github/workflows/meshery-cloud-release.yml
=> add doc build step

.github/workflows/meshery-cloud-release.yml
=> [CI] New step to install redocly

cypress/e2e/e2e/design_spec.js, cypress/support/constants.js
Failing design on empty design-file, enforces that the loaded design is correctly rendered on canvas.
=> cypress test: refer to a new private design-file for testing, fail test on empty design

cypress/e2e/e2e/design_spec.js
=> fix failing tests for upgrade in Meshery-extensions

test/main.go
=> log timestamps for checks

.github/workflows/meshery-cloud-release.yml
=> add environment variable as argument for Dockerfile

site/src/assets/data/faq/index.js
=> Add more FAQs

site/src/assets/data/faq/index.js
=> [Badges] Update FAQs

.github/workflows/meshery-cloud-release.yml
Dependent PR: https://github.com/layer5io/meshery-cloud/pull/1192
=> update meshery cloud release workflow

site/src/badgesInfo.json, site/src/sitecomponents/BadgeGrid/index.js
This PR fixes #124
Currently, I only added Achievement Badges in the JSON file and if it is good to go, then I will also add Project Badges into the JSON file
=> Badges are Dynamically rendered

email/recognition-program/layer5-recognition-program-2023.html
This PR updates 
- The graphic in the recognition program email template
- Text styling and coloring
- Fixed the Twitter icon 
https://github.com/layer5labs/meshery-extensions-packages/assets/51539117/8d3d71df-0ddf-48ce-9345-8de28c7b3104
=> Updated graphics and text in recognition program email

email/recognition-program/layer5-recognition-program-2023.html
Add full html email template - Layer5 Recognition Program
=> [Badge] Update layer5-recognition-program-2023.html

site/src/html.js
- The Current version has a loading animation with improper width and height.
- So, I had a discussion with @ritiksaxena124 to get the actual aspect ratio of this image and changed it.
=> Changed the Loading Animation resolution

.github/workflows/meshery-cloud-release.yml
This PR:
1. Add supports to auto lint UI and backend on each staging release
2. Remove unwanted steps
=> [CI] Update Meshery Cloud release process

.github/workflows/meshery-cloud-release.yml
=> Add missing path

site/src/html.js
Added the Google Tag Manager Scripts to the head and body.
=> Update html.js (GTM Script added)

design-embed/package.json
=> create dir for design-embed

.github/workflows/publish-meshery-embed-package.yml
=> [ci] fix: meshery embed workflow

.github/workflows/publish-meshery-embed-package.yml
=> [ci] use only single job in design-embed workflow

.github/workflows/publish-meshery-embed-package.yml
=> remove working dir

meshery-design-embed/package.json
=> Update package name package.json

.github/workflows/build-and-deploy-site.yml, .github/workflows/extension-test-on-pr.yml, .github/workflows/extension-test.yml, .github/workflows/meshery-cloud-build.yml, .github/workflows/meshery-cloud-release.yml, .github/workflows/publish-meshery-embed-package.yml
=> chore: bump action versions

.github/workflows/meshery-cloud-release.yml
=> ci: include git user credential

site/src/pages/index.js, site/src/sitecomponents/Footer/index.js
=> Fixed broken links

.github/workflows/meshery-cloud-release.yml
This PR avoids the Node 16 warning (hopefully) that we see here - https://github.com/layer5labs/meshery-extensions-packages/actions/runs/7646947869
=> Upgrade API Docs Workflow Step to fjogeleit/yaml-update-action@v0.13.2

.github/workflows/meshery-cloud-release.yml
Reverts layer5labs/meshery-extensions-packages#236
=> Revert "Update meshery-cloud-release.yml"

.github/workflows/meshery-cloud-release.yml
=> Env Var for Git version

.github/workflows/release-cloud-helm-chart.yml
=> [CI] Publish Cloud Helm Chart

meshery-design-embed/public/embedded-design-embed1.js, site/gatsby-config.js, site/package-lock.json, site/package.json
=> Implemented support for styled components in additional libraries.

.github/workflows/release-cloud-helm-chart.yml
=> fix release cloud helm chart workflow

site/src/badgesInfo.json, site/src/sitecomponents/BadgeGrid/index.js
A new section for Special Edition badges is added to the website. 
**Included badges in the Special Edition section are:**
1. CNCF Ambassador
2. Docker Captain
3. Hacktoberfest Contributor
=> [Badges Site] A section for special edition badges

.github/workflows/meshery-cloud-release.yml
=> peform cleanup after deployment

.github/workflows/extension-test-on-pr.yml
=> update testing workflow

.github/workflows/extension-test-on-pr.yml
=> pass env variables to test step

.github/workflows/extension-test-on-pr.yml, .github/workflows/workflow-dispatcher.yml
=> add env vars

.github/workflows/extension-test-on-pr.yml
=> checkout extensions on ui-tests

.github/workflows/extension-test-on-pr.yml
=> checkout meshery to ./meshery

.github/workflows/extension-test-on-pr.yml
=> Testing workflow fix

.github/workflows/extension-test-on-pr.yml
=> fix : test workflow

meshery-design-embed/public/embedded-design-embed1.js
This PR 
- removed the provided by
- added support to get the styles to the Embed design to support both dark and light theme  
=> enhanced embeded design

.github/workflows/extension-test-on-pr.yml
=> build graphql

.github/workflows/extension-test-on-pr.yml
=> checkout meshery before building graphql

.github/workflows/extension-test-on-pr.yml
=> dont show in code blocks

.github/workflows/extension-test-on-pr.yml
This PR fixes the Node 16 warning message
=> [CI] Extension Tests: Update hasuro/comment-progress to v2.3.0 in extension-test-on-pr.yml

.github/workflows/extension-test-on-pr.yml
This PR fixes the Node 12 warning.
=> [CI] Extension Tests: Update to helm/kind-action v1.10.0 in extension-test-on-pr.yml

.github/workflows/meshery-cloud-release.yml
=> Try sudo in staging deployments to overcome perms issue

.github/workflows/meshery-cloud-release.yml
=> chore: Update meshery-cloud-release.yml for staging and production deployments

meshery-design-embed/README.md
=> README: List of items not currently supported in embed mode

meshery-design-embed/README.md
=> update docs link

README.md
=> update readme adding details for directory structure

.github/workflows/extension-test-on-pr.yml
=> fix: invalid format test report on CI

.github/workflows/deploy-meshery-extensions-playground.yml
=> Workflow to rollout new kanvas deployment

.github/workflows/extension-test-on-pr.yml
Reverts layer5labs/meshery-extensions-packages#306
=> Revert "ci: refactor to new e2e test reporting"

.github/workflows/extension-test-on-pr.yml
https://github.com/actions/github-script?tab=readme-ov-file#reading-step-results
=> ci: refactor test reporter

.github/workflows/meshery-cloud-release.yml
This PR is a simple chore to keep actions up to date and to eliminate the "old Node.js" warning that we're gettinig on the deployment workflow.
=> [CI] upgrade action: fjogeleit/yaml-update-action@v0.15.0

.github/workflows/build-and-release-kanvas.yml
=> Reenable failure on release email

.github/workflows/extension-test-on-pr.yml
Reverts layer5labs/meshery-extensions-packages#332
=> Revert "make kanvas-prod to prod: include all extensions in build"

site/src/badgesInfo.json
=> Restructure new hacktoberfest badge

.github/workflows/build-and-release-kanvas.yml
=> add go.mod sync compatibility check

.github/workflows/build-and-deploy-meshery-extensions-playground.yml, .github/workflows/build-and-release-kanvas.yml
=> Package extension as part of `Kanvas build and rollout`

.github/workflows/build-and-release-kanvas.yml
=> Disable caching in build-and-release-kanvas workflow

.github/workflows/build-and-deploy-meshery-extensions-playground.yml
=> Upgrade GH Action azure/docker-login@v2

.github/workflows/build-and-release-kanvas.yml
This PR aligns the meshery-extensions build to better match that of Meshery UI's environment.
=> [CI] Update to Node 18 and match Meshery UI's build

.github/workflows/build-and-release-kanvas.yml
=> ci: fix release notes multiline

.github/workflows/meshery-cloud-build-reusable.yml
=> fix: wrong type

.github/workflows/meshery-cloud-build-reusable.yml, .github/workflows/meshery-cloud-on-pr.yml
=> fix: change number input as string because of gh bug

.github/workflows/extension-test-on-pr.yml, .github/workflows/extension-test-reusable.yml, .github/workflows/workflow-dispatcher.yml
=> fix: repository workflow dispatcher

.github/workflows/build-and-deploy-meshery-extensions-playground.yml, .github/workflows/build-and-release-kanvas.yml, .github/workflows/extension-test.yml
=> fix: fix typo on smoke data type

.github/workflows/bump-deps-meshery-and-extensions.yml
=> ci: fix the wrong check

.github/workflows/bump-deps-meshery-and-extensions.yml
=> ci: change the github actor

.github/workflows/production-smoke-test.yml
=> ci: remove default as conflicting with required

.github/workflows/build-and-deploy-meshery-extensions-playground.yml, .github/workflows/build-and-release-kanvas.yml, .github/workflows/production-smoke-test-reusable.yml
=> ci: reintroduce smoke test after success run on playground release

.github/workflows/meshery-cloud-build-reusable.yml
=> ci: change api schema validation command on PR cloud

.github/workflows/extension-test-reusable.yml
=> chore: fix format on comment and error on release

.github/actions/feature-list-action/main.go, .github/workflows/generate-feature-list.yml, feature_data.json
This PR updated the feature workflow script file to add a new column that'd help in mapping features in layer5/pricing page
=> Feature list new column added to support pricing page mapping

.github/workflows/meshery-cloud-release.yml
=> Update meshery-cloud-release.yml with secrets

.github/workflows/workflow-dispatcher.yml
=> Add secrets

.github/workflows/meshery-cloud-release.yml
Command to modify ingress for add cloud-ws.layer5.io.
=> Add command to apply ingress changes

.github/workflows/generate-feature-list.yml
=> ci: bypass git hooks

.github/workflows/generate-feature-list.yml
Reverts layer5labs/meshery-extensions-packages#397
=> Revert "ci: bypass git hooks"

.github/workflows/extension-test-reusable.yml
=> chore: directly download test results artifact from pr

.github/workflows/build-and-deploy-meshery-extensions-playground.yml
=> ci: add back smoke test

.github/workflows/extension-test-reusable.yml
=> chore: improve-compatibility-message

.github/workflows/meshery-cloud-release.yml
Disable deploy production in AWS EC2
This PR comments out AWS deployment.
=> Disable deploy production in AWS EC2

.github/workflows/extension-test-reusable.yml
=> fix: refactor extensions reusable test

.github/workflows/extension-test-reusable.yml
=> ci: fix e2e test command

.github/workflows/extension-test-relationship.yml
=> Ci: relationship test trigger

.github/workflows/extension-test-reusable.yml
=> ci: remove depends on comment on meshery extensions build

.github/actions/feature-list-action/main.go
=> fix: spreadsheets-pull-html-page

feature_data.json
Reverts layer5labs/meshery-extensions-packages#421
=> Revert "[Chore]: Update feature data"

.github/workflows/extension-test-relationship.yml, .github/workflows/extension-test-reusable.yml
This is for testing purpose will refactor to release based on the future
=> ci: add relationship report to meshery

.github/workflows/extension-test-relationship.yml
=> ci: add waiting for test completed

.github/workflows/extension-test-relationship.yml, .github/workflows/extension-test-reusable.yml
=> ci: fix wrong folder test result inside meshmap

.github/workflows/extension-test-relationship.yml
=> ci: fix missing relationship file

.github/workflows/extension-test-relationship.yml
=> ci: repository name should be a folder name

.github/workflows/workflow-dispatcher.yml
This PR propagates secrets necessary for the deployment of staging-cloud
=> [Chore] Addition of Metal02 secrets

.github/workflows/build-extension-reusable.yml
=> Update ubuntu-24.04 build-extension-reusable.yml

.github/workflows/build-and-release-kanvas.yml
=> Update ubuntu-24.04 build-and-release-kanvas.yml

.github/workflows/extension-test-reusable.yml
=> Update ubuntu-24.04 extension-test-reusable.yml

.github/workflows/build-and-deploy-meshery-extensions-playground-reusable.yml, .github/workflows/build-and-deploy-meshery-extensions-playground.yml, .github/workflows/build-and-deploy-site.yml, .github/workflows/build-and-release-kanvas.yml, .github/workflows/build-extension-reusable.yml, .github/workflows/bump-deps-meshery-and-extensions.yml, .github/workflows/extension-test-relationship.yml, .github/workflows/extension-test-reusable.yml, .github/workflows/generate-feature-list.yml, .github/workflows/meshery-cloud-build-reusable.yml, .github/workflows/meshery-cloud-build.yml, .github/workflows/meshery-cloud-release.yml, .github/workflows/notify-email.yml, .github/workflows/production-smoke-test-reusable.yml, .github/workflows/publish-meshery-embed-package.yml, .github/workflows/release-notes.yaml, .github/workflows/slack.yml, .github/workflows/update-extension-release.yaml, .github/workflows/verify-email.yml
This PR also disables smoke tests that are failing.
=> [chore] update to ubuntu-24.04

.github/workflows/build-and-release-kanvas.yml, .github/workflows/meshery-cloud-release.yml
=> update Go version to 1.23 in workflow files

.github/workflows/meshery-cloud-release.yml
=> Update workflow to use local values

.github/workflows/build-and-deploy-site.yml, site/Makefile
=> fix-missing-blob

.github/workflows/build-and-deploy-meshery-extensions-playground-reusable.yml
=> clean up checkout repos

.github/workflows/bump-deps-meshery-and-extensions.yml
=> add @layer5/schemas in bump-deps-meshery-ui workflow

.github/workflows/build-and-deploy-site.yml
This PR attempts to fix recent site deployment failures 
Ref: 
https://github.com/JamesIves/github-pages-deploy-action/tree/v4.6.1?tab=readme-ov-file#getting-started-airplane
=> Try adding write permission

.github/workflows/meshery-cloud-release.yml
=> new server folder

.github/workflows/meshery-cloud-build-reusable.yml
=> [meshery-cloud-build-reusable.yml] Include build comments; skip lint fixes

.github/workflows/meshery-cloud-build-reusable.yml
=> no more arm64

.github/workflows/meshery-cloud-build-reusable.yml
=> [CI] Add proper docker build context

.github/workflows/workflow-dispatcher.yml
=> Update workflow-dispatcher.yml for METAL04

.github/workflows/meshery-cloud-on-pr.yml
=> Set staging to metal05

.github/workflows/meshery-cloud-build-reusable.yml
This PR fixes the file paths for how metal05 is configured.
=> Update filepath for Staging deployments

.github/workflows/build-and-deploy-meshery-extensions-playground-reusable.yml, .github/workflows/meshery-cloud-build-reusable.yml, .github/workflows/meshery-cloud-on-pr.yml, .github/workflows/meshery-cloud-release.yml, .github/workflows/workflow-dispatcher.yml
=> refactor: standardize secret variable names for Metal configuration across workflows

.github/workflows/build-extension-reusable.yml, .github/workflows/meshery-cloud-build-reusable.yml, .github/workflows/meshery-cloud-on-pr.yml, .github/workflows/meshery-cloud-release.yml, .github/workflows/workflow-dispatcher.yml
=> refactor: remove redundant secret variables and update Go version in workflows
